import {loadState,saveState,resetState,createDefaultState} from './storage.js';
import {barChart,donutChart} from './charts.js';
import {clamp,pct,esc,fmtNumber,isoDate,dateBR,secondsToClock,minutesToClock,clockToMinutes,downloadJSON,debounce,normalizeText,uid,dayName} from './utils.js';
import {buildWeeklySchedule,eventsForDate,startOfWeek,dateFromWeekDay,weekKey,formatTimeOfDay,localDateISO} from './scheduler.js';

const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const view=$('#view'),loading=$('#loading-screen'),appShell=$('#app'),bottomNav=$('#bottom-nav');
let DATA={},state,route='dashboard',coursePage=1,editalPage=1,deferredInstall=null,courseFocusId=null,calendarWeekOffset=0,questionPrefill=null;
let timer={running:false,startedAt:0,elapsed:0,interval:null};

async function boot(){
  try{
    const [edital,course,coverage,weights,metadata,config,phrases,discursivas]=await Promise.all([
      './data/edital.json','./data/curso-gran.json','./data/cobertura-gran.json','./data/pesos.json','./data/metadata.json','./data/config-padrao.json','./data/frases-motivacionais.json','./data/temas-discursiva.json'
    ].map(u=>fetch(u).then(r=>{if(!r.ok)throw new Error(`Falha ao carregar ${u}`);return r.json()})));
    DATA={edital,course,coverage,weights,metadata,config,phrases,discursivas};state=loadState(config);const previousVisit=state.lastVisit;state.lastVisit=new Date().toISOString();saveState(state);applyTheme();populateTimerSubjects();bindGlobal();
    $('#app-version').textContent=`v${metadata.version}`;$('#updated-date').textContent=`Atualizado em ${dateBR(metadata.updatedAt)}`;loading.remove();appShell.hidden=false;bottomNav.hidden=false;navigate(location.hash.replace('#/','')||'dashboard',false);
    if('serviceWorker' in navigator){navigator.serviceWorker.register('./service-worker.js').then(()=>initEngagement(previousVisit)).catch(()=>initEngagement(previousVisit));}else initEngagement(previousVisit);
  }catch(err){loading.innerHTML=`<strong>Não foi possível carregar o projeto.</strong><small>${esc(err.message)}<br>Abra pelo GitHub Pages ou por um servidor local, não diretamente pelo arquivo index.html.</small>`}
}

function bindGlobal(){
  document.addEventListener('click',e=>{
    const nav=e.target.closest('[data-route]');if(nav){navigate(nav.dataset.route);$('#sidebar').classList.remove('open')}
  });
  $('#menu-button').onclick=()=>$('#sidebar').classList.toggle('open');
  $('#theme-toggle').onclick=()=>{state.settings.theme=state.settings.theme==='dark'?'light':'dark';save();applyTheme();render()};
  $('#timer-mini').onclick=()=>$('#timer-dialog').showModal();
  $('#timer-start').onclick=startTimer;$('#timer-pause').onclick=pauseTimer;$('#timer-finish').onclick=finishTimer;
  window.addEventListener('hashchange',()=>navigate(location.hash.replace('#/','')||'dashboard',false));
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#install-button').hidden=false});
  $('#install-button').onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#install-button').hidden=true};
  $('#import-confirm').onclick=importBackup;
}
function save(){saveState(state)}
function applyTheme(){document.documentElement.dataset.theme=state.settings.theme||'dark'}
function navigate(next,push=true){route=ROUTES[next]?next:'dashboard';if(push)location.hash=`#/${route}`;$$('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===route));const meta=ROUTES[route];$('#page-title').textContent=meta.title;$('#page-eyebrow').textContent=meta.eyebrow;render()}
function render(){const fn=ROUTES[route]?.render||renderDashboard;fn();updateSidebar()}
function updateSidebar(){const d=derived();const p=(d.editalDoneRatio+d.courseDoneRatio)/2;$('#sidebar-progress-label').textContent=pct(p);$('#sidebar-progress-bar').style.width=pct(p)}
function toast(message,type='success'){const n=document.createElement('div');n.className=`toast ${type}`;n.textContent=message;$('#toast-stack').append(n);setTimeout(()=>n.remove(),4200)}
function phraseOfDay(){if(!DATA.phrases?.length)return 'Um passo de cada vez.';const start=new Date(new Date().getFullYear(),0,0),now=new Date(),day=Math.floor((now-start)/86400000);return DATA.phrases[day%DATA.phrases.length].texto}
function randomPhrase(){return DATA.phrases?.length?DATA.phrases[Math.floor(Math.random()*DATA.phrases.length)].texto:phraseOfDay()}
function contentDays(){return [0,1,2,3,4,5]}
function weeklyContentMinutes(){return contentDays().reduce((a,d)=>a+Number(state.settings.dayMinutes[d]||0),0)}
function weeklyTotalMinutes(){return [0,1,2,3,4,5,6].reduce((a,d)=>a+Number(state.settings.dayMinutes[d]||0),0)}
function parseLocalDate(value,end=false){if(!value)return null;const [y,m,d]=String(value).split('-').map(Number);if(!y||!m||!d)return null;return new Date(y,m-1,d,end?23:12,end?59:0,end?59:0,0)}
function diffDays(a,b){return Math.floor((b-a)/86400000)}
function examDateValue(){return state.settings.objectiveExamDate||state.settings.targetDate||''}
function preparationReferenceDate(){return state.settings.preparationMode==='post'?state.settings.editalDate:state.settings.studyStartDate}
function preparationLabel(){return state.settings.preparationMode==='post'?'Pós-edital':'Pré-edital'}
function finalSprintStatus(date=new Date()){
  const exam=parseLocalDate(examDateValue(),true);if(!exam)return{active:false,daysLeft:null,examDate:null};
  const current=new Date(date.getFullYear(),date.getMonth(),date.getDate(),12),daysLeft=diffDays(current,exam),limit=Math.max(1,Number(state.settings.finalSprint?.days||15));
  return{active:daysLeft>=0&&daysLeft<limit,daysLeft,examDate:exam,limit};
}
function lessonBudgetForDate(date){
  if(date.getDay()===6)return 0;const base=Number(state.settings.dayMinutes[date.getDay()]||0),sprint=finalSprintStatus(date);
  return sprint.active?base*(1-Math.min(.9,Math.max(.5,Number(state.settings.finalSprint?.practiceShare??.6)))):base;
}
function weeklyLessonMinutes(baseDate=new Date()){
  const start=startOfWeek(baseDate);let total=0;for(const d of contentDays())total+=lessonBudgetForDate(dateFromWeekDay(start,d));return total;
}
function rawSubjectHours(){const subjects=objectiveSubjects(),by={};subjects.forEach(s=>by[s]={total:0,done:0,items:DATA.weights[s]||0});DATA.course.forEach(x=>{if(!by[x.materia])return;by[x.materia].total+=x.duracaoSegundos;if(statusCourse(x.id).watched)by[x.materia].done+=x.duracaoSegundos});return by}
function questionAnalytics(){
  const subjects=Object.fromEntries(objectiveSubjects().map(s=>[s,{subject:s,questions:0,correct:0,errors:0,weight:DATA.weights[s]||0}])),topics={};
  const add=(subject,topicId,questions,correct)=>{questions=Math.max(0,Number(questions||0));correct=clamp(Number(correct||0),0,questions);if(!questions)return;subjects[subject]??={subject,questions:0,correct:0,errors:0,weight:DATA.weights[subject]||0};subjects[subject].questions+=questions;subjects[subject].correct+=correct;subjects[subject].errors+=questions-correct;if(topicId){const item=DATA.edital.find(x=>x.id===topicId);if(item){topics[topicId]??={topicId,subject:item.materia,item:item.item,label:item.conteudo,questions:0,correct:0,errors:0,weight:DATA.weights[item.materia]||0};topics[topicId].questions+=questions;topics[topicId].correct+=correct;topics[topicId].errors+=questions-correct;}}};
  DATA.edital.forEach(x=>{const st=statusEdital(x.id);add(x.materia,x.id,st.questions,st.correct)});
  state.questions.forEach(q=>add(q.subject,q.topicId||null,q.questions,q.correct));
  const subjectRows=Object.values(subjects).map(x=>({...x,accuracy:x.questions?x.correct/x.questions:0,errorRate:x.questions?x.errors/x.questions:0}));
  const topicRows=Object.values(topics).map(x=>({...x,accuracy:x.questions?x.correct/x.questions:0,errorRate:x.questions?x.errors/x.questions:0,score:x.errors*3+(x.questions?x.errors/x.questions:0)*10+(x.weight/120)*5}));
  const recommendations=topicRows.filter(x=>x.errors>0).sort((a,b)=>b.score-a.score||b.errors-a.errors).slice(0,12);
  const mostErrors=subjectRows.filter(x=>x.questions).sort((a,b)=>b.errors-a.errors||b.errorRate-a.errorRate)[0]||null;
  const mostCorrect=subjectRows.filter(x=>x.questions).sort((a,b)=>b.correct-a.correct||b.accuracy-a.accuracy)[0]||null;
  const recent=(days)=>{const cutoff=new Date();cutoff.setHours(0,0,0,0);cutoff.setDate(cutoff.getDate()-(days-1));return state.questions.filter(q=>{const d=parseLocalDate(q.date);return d&&d>=cutoff}).reduce((a,q)=>a+Number(q.questions||0),0)};
  const totalQuestions=subjectRows.reduce((a,x)=>a+x.questions,0),totalCorrect=subjectRows.reduce((a,x)=>a+x.correct,0),totalErrors=totalQuestions-totalCorrect;
  return{subjects:subjectRows,topics:topicRows,recommendations,mostErrors,mostCorrect,totalQuestions,totalCorrect,totalErrors,accuracy:totalQuestions?totalCorrect/totalQuestions:0,recent7:recent(7),recent15:recent(15),recent30:recent(30)};
}
function weakStudyTargets(){
  const qa=questionAnalytics();if(qa.recommendations.length)return qa.recommendations.map(x=>({materia:x.subject,topicId:x.topicId,topicLabel:`Item ${x.item} · ${x.label}`,errors:x.errors,errorRate:x.errorRate}));
  return qa.subjects.filter(x=>x.errors>0).sort((a,b)=>b.errors-a.errors||b.errorRate-a.errorRate).slice(0,8).map(x=>({materia:x.subject,topicId:null,topicLabel:'Revisão geral da matéria',errors:x.errors,errorRate:x.errorRate}));
}
function capacityUntilExam(examDate){
  const exam=parseLocalDate(examDate,true);if(!exam)return null;const ref=parseLocalDate(preparationReferenceDate())||new Date(),today=new Date();today.setHours(12,0,0,0);let cursor=new Date(Math.max(today.getTime(),ref.getTime())),total=0,guard=0;
  while(cursor<=exam&&guard++<1000){total+=lessonBudgetForDate(cursor);cursor.setDate(cursor.getDate()+1)}return total;
}
function scheduleAnalysis(){
  const by=rawSubjectHours(),remainingSec=Object.values(by).reduce((a,x)=>a+Math.max(0,x.total-x.done),0),remainingMin=remainingSec/60,weekly=weeklyLessonMinutes(),weeksNeeded=weekly>0?remainingMin/weekly:Infinity;
  const projected=new Date();if(Number.isFinite(weeksNeeded))projected.setDate(projected.getDate()+Math.ceil(weeksNeeded*7));
  const reference=preparationReferenceDate(),referenceDate=parseLocalDate(reference),exam=examDateValue(),examDate=parseLocalDate(exam,true),now=new Date(),capacity=exam?capacityUntilExam(exam):null;
  const daysSinceStart=referenceDate?Math.max(0,diffDays(referenceDate,now)):null,daysToExam=examDate?Math.max(0,diffDays(now,examDate)):null,cycleDays=referenceDate&&examDate?Math.max(0,diffDays(referenceDate,examDate)):null,weeksAvailable=daysToExam===null?null:daysToExam/7;
  const requiredWeekly=weeksAvailable&&weeksAvailable>0?remainingMin/weeksAvailable:null,insufficient=Boolean(examDate&&remainingSec>0&&(capacity===null||capacity<remainingMin));
  return{remainingSec,remainingMin,weekly,weeksNeeded,projectedDate:Number.isFinite(weeksNeeded)?projected:null,reference,referenceDate,exam,examDate,daysSinceStart,daysToExam,cycleDays,weeksAvailable,capacityMinutes:capacity,requiredWeekly,insufficient,finalSprint:finalSprintStatus()};
}
function priorityOrder(){const by=rawSubjectHours();return objectiveSubjects().filter(s=>Math.max(0,by[s].total-by[s].done)>0).sort((a,b)=>(DATA.weights[b]||0)-(DATA.weights[a]||0));}
function dateFull(){return new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date())}
async function syncReminderConfig(){
  if(!('serviceWorker' in navigator))return;
  try{const reg=await navigator.serviceWorker.ready;const cfg=state.settings.notifications||{};reg.active?.postMessage({type:'REMINDER_CONFIG',enabled:Boolean(cfg.enabled),inactivityHours:Number(cfg.inactivityHours||24),lastOpen:Date.now(),phrase:randomPhrase()});
    if(cfg.enabled&&'periodicSync' in reg){try{await reg.periodicSync.register('bacen-study-reminder',{minInterval:12*60*60*1000})}catch{}}
  }catch{}
}
async function initEngagement(previousVisit){
  const cfg=state.settings.notifications||{},gap=previousVisit?(Date.now()-new Date(previousVisit).getTime())/3600000:0;
  if(previousVisit&&gap>=Number(cfg.inactivityHours||24)){toast(`Você ficou ${Math.floor(gap)}h sem abrir o plano. ${randomPhrase()}`,'success');if(cfg.enabled&&'Notification' in window&&Notification.permission==='granted'){try{const reg=await navigator.serviceWorker.ready;await reg.showNotification('BACEN Estudos TI',{body:randomPhrase(),icon:'./assets/favicon.svg',badge:'./assets/favicon.svg',tag:'bacen-return'});}catch{}}}
  syncReminderConfig();
}
async function enableNotifications(){
  if(!('Notification' in window)){toast('Este navegador não oferece notificações Web.','error');return}
  const perm=await Notification.requestPermission();if(perm!=='granted'){toast('Permissão de notificações não concedida.','error');return}
  state.settings.notifications.enabled=true;save();await syncReminderConfig();toast('Lembretes ativados. O suporte com o site fechado depende do navegador/PWA.');renderConfig();
}

function statusEdital(id){return state.edital[id]||{done:false,review:false,questions:0,correct:0,completedAt:null}}
function statusCourse(id){return state.course[id]||{watched:false,review:false,completedAt:null}}
function objectiveSubjects(){return Object.keys(DATA.weights)}
function derived(){
  const editalDone=DATA.edital.filter(x=>statusEdital(x.id).done).length,courseTotalSec=DATA.course.reduce((a,x)=>a+x.duracaoSegundos,0),courseDoneSec=DATA.course.reduce((a,x)=>a+(statusCourse(x.id).watched?x.duracaoSegundos:0),0),watchedCount=DATA.course.filter(x=>statusCourse(x.id).watched).length,timerSec=state.timerSessions.reduce((a,x)=>a+Number(x.seconds||0),0),qa=questionAnalytics();
  return{editalDone,editalDoneRatio:editalDone/DATA.edital.length,courseTotalSec,courseDoneSec,courseDoneRatio:courseTotalSec?courseDoneSec/courseTotalSec:0,watchedCount,questions:qa.totalQuestions,correct:qa.totalCorrect,errors:qa.totalErrors,accuracy:qa.accuracy,timerSec};
}
function allocations(){
  const subjects=objectiveSubjects(),by=rawSubjectHours(),remainingSum=subjects.reduce((a,s)=>a+Math.max(0,by[s].total-by[s].done),0),pendingItems=subjects.reduce((a,s)=>a+(by[s].total-by[s].done>0?by[s].items:0),0),analysis=scheduleAnalysis(),priorityMode=Boolean(state.settings.autoPriority&&analysis.insufficient),qa=questionAnalytics();
  let lw=priorityMode?.25:Number(state.settings.loadWeight||.5),ew=priorityMode?.75:Number(state.settings.examWeight||.5);const wSum=lw+ew||1,weeklyMinutes=weeklyLessonMinutes(),weakMap=Object.fromEntries(qa.subjects.map(x=>[x.subject,x.errorRate]));
  let rows=subjects.map(s=>{const x=by[s],rem=Math.max(0,x.total-x.done),loadShare=remainingSum?rem/remainingSum:0,examShare=rem>0&&pendingItems?x.items/pendingItems:0,base=(loadShare*lw+examShare*ew)/wSum,weakness=analysis.finalSprint.active?Number(weakMap[s]||0):0;return{materia:s,total:x.total,done:x.done,remaining:rem,items:x.items,loadShare,examShare,baseShare:base,weakness}});
  const denom=rows.reduce((a,x)=>a+(x.remaining>0?x.baseShare*(1+(.35*x.weakness)):0),0)||1;
  rows=rows.map(x=>{const share=x.remaining>0?(x.baseShare*(1+(.35*x.weakness)))/denom:0;return{...x,share,weeklyMinutes:share*weeklyMinutes,weeks:share*weeklyMinutes?x.remaining/60/(share*weeklyMinutes/60):0,priorityMode}}).sort((a,b)=>b.share-a.share);return rows;
}
function planBaseDate(offset=0){const d=new Date();d.setDate(d.getDate()+Number(offset||0)*7);return d}
function reservedLessonIds(exceptKey=''){const ids=new Set();Object.entries(state.weeklyPlans||{}).forEach(([key,plan])=>{if(key===exceptKey)return;(plan.events||[]).forEach(e=>{if(e.type==='lesson'&&e.lessonId)ids.add(e.lessonId)})});return ids}
function getWeeklyPlan(baseDate=new Date(),force=false){
  const key=weekKey(baseDate);if(!force&&state.weeklyPlans?.[key])return state.weeklyPlans[key];
  const watchedIds=new Set(DATA.course.filter(x=>statusCourse(x.id).watched).map(x=>x.id));
  const plan=buildWeeklySchedule({course:DATA.course,watchedIds,reservedLessonIds:reservedLessonIds(key),allocations:allocations(),dayMinutes:state.settings.dayMinutes,dayStartTimes:state.settings.dayStartTimes,breakMinutes:state.settings.breakMinutes,saturday:state.settings.saturday,baseDate,examDate:examDateValue(),finalSprint:state.settings.finalSprint,weakTopics:weakStudyTargets()});
  state.weeklyPlans??={};state.weeklyPlans[key]=plan;save();return plan
}
function invalidateWeeklyPlans(){state.weeklyPlans={};save()}
function todayEvents(){return eventsForDate(getWeeklyPlan(new Date()),isoDate())}
function eventDone(e){return e.type==='lesson'?statusCourse(e.lessonId).watched:Boolean(state.weeklyChecks?.[`${e.date}-${e.id}`])}
function toggleEventDone(e){
  if(e.type==='lesson'){const st=statusCourse(e.lessonId),watched=!st.watched;state.course[e.lessonId]={...st,watched,completedAt:watched?(st.completedAt||isoDate()):null};}
  else{const k=`${e.date}-${e.id}`;state.weeklyChecks[k]=!state.weeklyChecks[k];}
  save();
}
function openLesson(id,preferExternal=false){
  const lesson=DATA.course.find(x=>x.id===id);if(!lesson)return;
  const direct=state.lessonLinks?.[id];
  if(preferExternal&&direct){window.open(direct,'_blank','noopener');return}
  courseFocusId=id;navigate('curso');requestAnimationFrame(()=>document.querySelector('[data-focus-lesson]')?.scrollIntoView({behavior:'smooth',block:'start'}));
}
function setLessonLink(id){
  const current=state.lessonLinks?.[id]||'';const value=prompt('Cole o link direto desta aula no Gran. Deixe vazio para remover.',current);if(value===null)return;
  state.lessonLinks??={};const clean=value.trim();if(clean&&!/^https?:\/\//i.test(clean)){toast('Use um link iniciado por http:// ou https://.','error');return}if(clean)state.lessonLinks[id]=clean;else delete state.lessonLinks[id];save();renderCourse();toast(clean?'Link direto da aula salvo.':'Link removido.');
}
function scheduleEventTask(e){
  if(e.type==='lesson')return `<div class="task lesson-task ${eventDone(e)?'done':''}" data-open-lesson="${e.lessonId}"><button class="check-btn ${eventDone(e)?'on':''}" data-toggle-event="${e.id}" title="Marcar aula como assistida">✓</button><div class="task-copy"><strong>${esc(e.materia)} · Tópico ${esc(e.topico)} · Aula ${esc(e.numero)}</strong><span>${esc(e.titulo)}</span><small>${formatTimeOfDay(e.startMinute)}–${formatTimeOfDay(e.endMinute)} · ${esc(e.professor||'Professor não informado')}</small></div><div class="task-side"><span class="task-time">${secondsToClock(e.duracaoSegundos)}</span>${state.lessonLinks?.[e.lessonId]?`<button class="tiny-link" data-open-gran="${e.lessonId}" title="Abrir link direto no Gran">Gran ↗</button>`:''}</div></div>`;
  return `<div class="task practice-task ${eventDone(e)?'done':''} ${e.finalSprint||e.smart?'smart-practice':''}" data-practice-route="${esc(e.route||'hoje')}" data-practice-subject="${esc(e.subject||'')}" data-practice-topic="${esc(e.topicId||'')}"><button class="check-btn ${eventDone(e)?'on':''}" data-toggle-event="${e.id}">✓</button><div class="task-copy"><strong>${esc(e.materia)}</strong><span>${esc(e.titulo)}</span><small>${formatTimeOfDay(e.startMinute)}–${formatTimeOfDay(e.endMinute)} · ${e.smart?'Priorizado pelos seus erros':'Bloco de prática'}</small></div><span class="task-time">${minutesToClock(e.endMinute-e.startMinute)}</span></div>`
}
function bindScheduleTasks(events,rerender){
  $$('[data-toggle-event]').forEach(b=>b.onclick=ev=>{ev.stopPropagation();const item=events.find(x=>x.id===b.dataset.toggleEvent);if(item){toggleEventDone(item);rerender()}});
  $$('[data-open-lesson]').forEach(el=>el.onclick=()=>openLesson(el.dataset.openLesson));
  $$('[data-open-gran]').forEach(b=>b.onclick=ev=>{ev.stopPropagation();openLesson(b.dataset.openGran,true)});
  $$('[data-practice-route]').forEach(el=>el.onclick=ev=>{if(ev.target.closest('[data-toggle-event]'))return;const target=events.find(x=>x.id===el.querySelector('[data-toggle-event]')?.dataset.toggleEvent);if(el.dataset.practiceRoute==='questoes'){questionPrefill={subject:el.dataset.practiceSubject||target?.subject||'',topicId:el.dataset.practiceTopic||target?.topicId||''};}navigate(el.dataset.practiceRoute)});
}
function courseBySubject(){const o={};objectiveSubjects().forEach(s=>o[s]={total:0,done:0});DATA.course.forEach(x=>{if(!o[x.materia])return;o[x.materia].total+=x.duracaoSegundos;if(statusCourse(x.id).watched)o[x.materia].done+=x.duracaoSegundos});return o}
function lessonProgress(m){const g=courseBySubject()[m];return g&&g.total?g.done/g.total:0}

function renderDashboard(){
  const d=derived(),alloc=allocations(),studyWeek=weeklyTotalMinutes(),timeline=scheduleAnalysis(),qa=questionAnalytics(),top=alloc.slice(0,5),sprint=timeline.finalSprint;
  const startLabel=timeline.reference?dateBR(timeline.reference):'não informada',examLabel=timeline.exam?dateBR(timeline.exam):'não informada';
  view.innerHTML=`<div class="fade-in">
    ${sprint.active?`<div class="sprint-banner"><div><span class="eyebrow">Reta final automática</span><strong>Faltam ${sprint.daysLeft} dias para a primeira prova objetiva.</strong><p>O calendário passou a reservar a maior parte do tempo para revisão e questões, priorizando os tópicos em que você mais erra.</p></div><button class="primary" data-route="revisoes">Ver revisões sugeridas</button></div>`:''}
    <div class="hero">
      <div class="hero-card"><span class="eyebrow">${preparationLabel()} · início considerado ${esc(startLabel)} · ${esc(dateFull())}</span><h2>Seu caminho para o BACEN TI em um só lugar.</h2><p>Acompanhe edital, 916 videoaulas, desempenho em questões, erros por tópico, revisões inteligentes e um calendário que muda automaticamente na reta final.</p><div class="hero-actions"><button class="primary" data-route="hoje">Começar estudo de hoje</button><button class="secondary" data-route="plano">Ver plano semanal</button></div></div>
      <div class="hero-stats card"><div class="hero-stat"><small>Tempo semanal</small><strong>${minutesToClock(studyWeek)}</strong></div><div class="hero-stat"><small>Curso restante</small><strong>${secondsToClock(d.courseTotalSec-d.courseDoneSec)}</strong></div><div class="hero-stat"><small>Início considerado</small><strong class="small-stat">${esc(startLabel)}</strong></div><div class="hero-stat"><small>${timeline.exam?'Prova objetiva':'Questões'}</small><strong class="small-stat">${timeline.exam?esc(examLabel):fmtNumber(d.questions)}</strong></div></div>
    </div>
    <div class="grid kpis">
      ${kpi('Edital verticalizado',pct(d.editalDoneRatio),`${d.editalDone} de ${DATA.edital.length} tópicos`,'☷')}
      ${kpi('Curso Gran',pct(d.courseDoneRatio),`${secondsToClock(d.courseDoneSec)} de ${secondsToClock(d.courseTotalSec)}`,'▶')}
      ${kpi('Precisão em questões',pct(d.accuracy,1),`${fmtNumber(d.correct)} acertos · ${fmtNumber(d.errors)} erros`,'✓')}
      ${kpi('Foco registrado',secondsToClock(d.timerSec),`${state.timerSessions.length} sessões`,'◉')}
    </div>
    <div class="grid two" style="margin-bottom:16px">
      <div class="card quote-card"><span class="eyebrow">Frase do dia · base com 500 frases</span><h3>“${esc(phraseOfDay())}”</h3><p>As frases também alimentam os lembretes de inatividade quando o navegador oferecer suporte.</p></div>
      <div class="card timeline-card ${timeline.insufficient?'risk':'ok'}"><div class="card-title"><div><h3>Análise do cronograma</h3><p>${preparationLabel()} · ${state.settings.preparationMode==='post'?`edital ${dateBR(state.settings.editalDate)} → prova ${examLabel}`:`estudos iniciados em ${startLabel}${timeline.exam?` → prova ${examLabel}`:''}`}</p></div><span class="badge ${timeline.insufficient?'high':'done'}">${timeline.insufficient?'Priorizar':'Ritmo atual'}</span></div><strong class="timeline-big">${timeline.projectedDate?timeline.projectedDate.toLocaleDateString('pt-BR'):'Defina horas de estudo'}</strong><p>${timeline.insufficient?`A capacidade de aulas até a prova é menor que a carga restante. O rateio reforça o peso da prova e a reta final reforça erros, questões e revisões.`:`${timeline.exam?`Capacidade estimada até a prova: ${minutesToClock(timeline.capacityMinutes||0)}.`:'Conclusão projetada do conteúdo objetivo no ritmo atual.'}`}</p><button class="secondary" data-route="plano">Analisar detalhes</button></div>
    </div>
    <div class="grid two question-intelligence" style="margin-bottom:16px">
      <div class="card"><div class="card-title"><div><h3>Inteligência de questões</h3><p>O sistema acompanha volume, acertos e erros por matéria.</p></div><span class="badge">${fmtNumber(qa.recent7)} nos últimos 7 dias</span></div><div class="question-mini-grid"><div><small>Mais erros</small><strong>${qa.mostErrors?esc(shortMatter(qa.mostErrors.subject)):'—'}</strong><span>${qa.mostErrors?`${qa.mostErrors.errors} erros · ${pct(qa.mostErrors.errorRate,0)}`:'Registre questões'}</span></div><div><small>Mais acertos</small><strong>${qa.mostCorrect?esc(shortMatter(qa.mostCorrect.subject)):'—'}</strong><span>${qa.mostCorrect?`${qa.mostCorrect.correct} acertos · ${pct(qa.mostCorrect.accuracy,0)}`:'Registre questões'}</span></div><div><small>Últimos 15 dias</small><strong>${fmtNumber(qa.recent15)}</strong><span>questões registradas por sessão</span></div></div><button class="secondary" data-route="questoes" style="width:100%;margin-top:14px">Abrir análise de questões</button></div>
      <div class="card"><div class="card-title"><div><h3>Revisões sugeridas</h3><p>Tópicos ordenados pelos seus erros e pelo peso da matéria.</p></div><span class="badge review">${qa.recommendations.length}</span></div>${qa.recommendations.slice(0,4).map((x,i)=>`<div class="smart-review-line"><span class="rank">${i+1}</span><div><strong>${esc(shortMatter(x.subject))} · Item ${esc(x.item)}</strong><small>${esc(x.label)}</small></div><span>${x.errors} erros</span></div>`).join('')||'<div class="empty mini">Ainda não há erros por tópico suficientes para sugerir uma revisão.</div>'}<button class="secondary" data-route="revisoes" style="width:100%;margin-top:14px">Ver fila inteligente</button></div>
    </div>
    <div class="grid two">
      <div class="card"><div class="card-title"><div><h3>Progresso por matéria</h3><p>Percentual concluído pelas horas das videoaulas.</p></div><span class="badge">Curso Gran</span></div><div class="chart-wrap"><canvas id="subject-chart"></canvas></div></div>
      <div class="card"><div class="card-title"><div><h3>Distribuição do estudo</h3><p>Rateio recomendado da semana${sprint.active?' com ajuste pelos seus erros':''}.</p></div><span class="badge">Dinâmico</span></div><div class="stats-list">${top.map(x=>statLine(x.materia,x.share,minutesToClock(x.weeklyMinutes))).join('')}</div><button class="secondary" data-route="plano" style="width:100%;margin-top:12px">Abrir rateio completo</button></div>
    </div>
    <div class="grid two" style="margin-top:16px">
      <div class="card"><div class="card-title"><div><h3>Próximas prioridades</h3><p>Matérias com maior participação no rateio atual.</p></div></div>${top.map((x,i)=>`<div class="progress-row"><div><span>${i+1}. ${esc(x.materia)}</span><span>${minutesToClock(x.weeklyMinutes)}/sem</span></div><div class="progress"><i style="width:${pct(x.share)}"></i></div></div>`).join('')}</div>
      <div class="card"><div class="card-title"><div><h3>Progresso global do curso</h3><p>Horas concluídas versus horas pendentes.</p></div></div><div class="chart-wrap"><canvas id="donut-chart"></canvas></div><div class="legend"><span><i style="background:var(--accent)"></i>Concluído</span><span><i style="background:var(--accent-2)"></i>Pendente</span></div></div>
    </div>
  </div>`;
  requestAnimationFrame(()=>{const by=courseBySubject();barChart($('#subject-chart'),objectiveSubjects().map(shortMatter),objectiveSubjects().map(s=>Math.round((by[s].done/(by[s].total||1))*100)),{max:100});donutChart($('#donut-chart'),[d.courseDoneSec,d.courseTotalSec-d.courseDoneSec],['concluído','pendente'])})
}
function kpi(label,value,sub,icon){return`<div class="card kpi"><div class="kpi-head"><span>${label}</span><span class="kpi-icon">${icon}</span></div><strong>${value}</strong><small>${sub}</small></div>`}
function statLine(label,ratio,value){return`<div class="stats-line"><span>${esc(label)}</span><div class="progress"><i style="width:${pct(ratio)}"></i></div><span>${value}</span></div>`}
function shortMatter(s){const m={'Língua Portuguesa':'Português','Noções de Lógica e Estatística':'Lógica/Estat.','Direito Administrativo':'Dir. Adm.','Fundamentos de Macroeconomia e Microeconomia':'Economia','Ciência de Dados':'Ciência Dados','Segurança da Informação':'Segurança','Engenharia de Software':'Eng. Software','Infraestrutura em TI':'Infra TI','Bancos de Dados':'BD','Gestão em TI':'Gestão TI'};return m[s]||s}

function renderToday(){
  const day=new Date().getDay(),mins=Number(state.settings.dayMinutes[day]||0),events=todayEvents(),sat=day===6,free=mins<=0,plan=getWeeklyPlan(new Date()),summary=plan.daySummary?.[isoDate()]||{},sprint=finalSprintStatus(),qa=questionAnalytics();
  const title=free?'Dia sem carga definida':sat?'Revisar, testar e consolidar.':sprint.active?'Reta final: erros, questões, revisão e aulas essenciais.':'Aulas reais planejadas para hoje.';
  const desc=free?'Você deixou este dia com 0:00. Se quiser estudar, basta informar um tempo no Plano de Estudos.':sat?`Tempo disponível hoje: ${minutesToClock(mins)}. O sábado permanece voltado à consolidação.`:sprint.active?`Faltam ${sprint.daysLeft} dias para a prova. ${minutesToClock(Number(summary.practiceMinutes||0))} de hoje foram reservados para revisão/questões, priorizando seus erros.`:`Tempo disponível hoje: ${minutesToClock(mins)}. O sistema selecionou aulas reais da grade e respeitou suas durações.`;
  view.innerHTML=`<div class="fade-in">${sprint.active?`<div class="sprint-banner compact"><div><span class="eyebrow">Reta final · ${sprint.daysLeft} dias</span><strong>Mais prática, menos dispersão.</strong><p>Revisões e questões são direcionadas aos tópicos com maior número de erros.</p></div></div>`:''}<div class="today-focus">
    <div class="card focus-block"><span class="eyebrow">${dayName(day)} · ${esc(dateFull())} · ${preparationLabel()}</span><h2>${title}</h2><p style="color:var(--muted)">${desc}</p><div class="hero-actions"><button class="primary" id="today-timer">Abrir cronômetro</button><button class="secondary" data-route="calendario">Ver calendário</button><button class="secondary" data-route="plano">Ajustar tempo</button></div></div>
    <div class="card"><div class="card-title"><div><h3>Meta do dia</h3><p>${sat?'Estrutura recomendada de sábado':sprint.active?'Aulas + prática orientada pelos erros':'Matéria, tópico e aula exatos'}</p></div><span class="badge">${minutesToClock(mins)}</span></div><div class="task-list">${events.length?events.map(scheduleEventTask).join(''):`<div class="empty"><strong>Sem estudo programado</strong>${free?'Ajuste o tempo deste dia ou use-o para descanso.':'Nenhuma aula pendente coube no tempo disponível. Aumente a janela ou recalcule a semana.'}</div>`}</div>${Number(summary.unused||0)>0?`<p class="helper" style="margin-top:12px">Margem livre hoje: ${minutesToClock(summary.unused)}. O calendário não corta aulas no meio.</p>`:''}</div>
  </div>
  <div class="grid two" style="margin-top:16px"><div class="card"><div class="card-title"><div><h3>Continuação do ciclo</h3><p>O rateio define a prioridade; na reta final, erros por matéria também influenciam a distribuição.</p></div></div>${state.settings.cycle.map((s,i)=>`<div class="progress-row"><div><span>${i+1}. ${esc(s)}</span><span>${minutesToClock(allocations().find(x=>x.materia===s)?.weeklyMinutes||0)}</span></div><div class="progress"><i style="width:${pct(lessonProgress(s))}"></i></div></div>`).join('')}</div>
  <div class="card"><div class="card-title"><div><h3>Radar de erros</h3><p>Use isto para decidir o que revisar quando houver tempo extra.</p></div><span class="badge high">${qa.totalErrors} erros</span></div>${qa.recommendations.slice(0,5).map(x=>`<div class="smart-review-line"><div><strong>${esc(shortMatter(x.subject))} · Item ${esc(x.item)}</strong><small>${esc(x.label)}</small></div><span>${x.errors} erros</span></div>`).join('')||'<div class="empty mini">Registre questões por tópico para ativar o radar.</div>'}<button class="secondary" data-route="revisoes" style="width:100%;margin-top:12px">Abrir revisões</button></div></div></div>`;
  $('#today-timer').onclick=()=>$('#timer-dialog').showModal();bindScheduleTasks(events,renderToday)
}
function renderPlan(){
  const a=allocations(),analysis=scheduleAnalysis(),contentMins=weeklyContentMinutes(),lessonMins=weeklyLessonMinutes(),satMins=Number(state.settings.dayMinutes[6]||0),total=weeklyTotalMinutes(),priority=priorityOrder(),weekPlan=getWeeklyPlan(new Date()),sprint=analysis.finalSprint,mode=state.settings.preparationMode||'pre';
  const statusText=mode==='post'&&!state.settings.editalDate?'No pós-edital, informe a data de publicação do edital para definir o início oficial da janela.':!analysis.exam?'Informe a data da primeira prova objetiva para comparar o ritmo e ativar automaticamente a reta final.':analysis.insufficient?'O tempo disponível não comporta toda a carga pendente até a prova objetiva.':'O tempo atual comporta a carga objetiva restante até a prova, considerando a estratégia de reta final.';
  const lessonEvents=weekPlan.events.filter(e=>e.type==='lesson'),plannedLessonMin=lessonEvents.reduce((n,e)=>n+(e.endMinute-e.startMinute),0),practiceMin=weekPlan.events.filter(e=>e.type==='practice').reduce((n,e)=>n+(e.endMinute-e.startMinute),0),unused=Object.values(weekPlan.unusedByDay||{}).reduce((x,y)=>x+Number(y||0),0);
  const referenceLabel=analysis.reference?dateBR(analysis.reference):'—';
  view.innerHTML=`<div class="fade-in"><div class="section-head"><div><h2>Plano semanal adaptativo</h2><p>As datas definem a fase da preparação; o calendário usa aulas reais e muda automaticamente nos últimos 15 dias.</p></div><div class="hero-actions"><span class="badge">${minutesToClock(total)} por semana</span><button class="primary" data-route="calendario">Abrir calendário</button></div></div>
  <div class="card preparation-card"><div class="card-title"><div><h3>Fase da preparação e datas</h3><p>No pré-edital, o sistema considera a data em que você iniciou os estudos. No pós-edital, a referência oficial passa a ser publicação do edital → primeira prova objetiva.</p></div><span class="badge ${mode==='post'?'high':'done'}">${preparationLabel()}</span></div><div class="prep-date-grid"><label class="field">Situação<select id="prep-mode"><option value="pre" ${mode==='pre'?'selected':''}>Pré-edital</option><option value="post" ${mode==='post'?'selected':''}>Pós-edital</option></select></label><label class="field">Data de início dos seus estudos<input type="date" id="study-start-date" value="${esc(state.settings.studyStartDate||'')}"></label><label class="field">Data de publicação do edital<input type="date" id="edital-date" value="${esc(state.settings.editalDate||'')}"></label><label class="field">Data da 1ª prova objetiva<input type="date" id="objective-exam-date" value="${esc(examDateValue())}"></label></div><p class="helper">Todos os campos são livres para alteração. ${mode==='pre'?`Referência atual: início dos estudos em <strong>${referenceLabel}</strong>.`:`Referência atual: edital em <strong>${referenceLabel}</strong> até a primeira prova objetiva.`}</p><div class="hero-stats prep-stats"><div class="hero-stat"><small>Início considerado</small><strong class="small-stat">${referenceLabel}</strong></div><div class="hero-stat"><small>Dias desde o início</small><strong>${analysis.daysSinceStart??'—'}</strong></div><div class="hero-stat"><small>Dias até a prova</small><strong>${analysis.daysToExam??'—'}</strong></div><div class="hero-stat"><small>Janela total</small><strong>${analysis.cycleDays!==null?`${analysis.cycleDays} dias`:'—'}</strong></div></div></div>
  ${sprint.active?`<div class="sprint-banner" style="margin-top:16px"><div><span class="eyebrow">Reta final ativa · últimos ${sprint.limit} dias</span><strong>Faltam ${sprint.daysLeft} dias para a prova objetiva.</strong><p>Em segunda–sexta e domingo, 60% da janela passa para revisão + questões. O sábado passa a 40% revisão, 40% questões, 15% simulado e 5% discursiva. Os tópicos com mais erros entram primeiro.</p></div><button class="primary" data-route="questoes">Ver desempenho</button></div>`:''}
  <div class="card" style="margin-top:16px"><div class="card-title"><div><h3>Tempo disponível por dia</h3><p>Segunda a sexta e domingo recebem conteúdo novo; na reta final parte desse tempo é automaticamente desviada para revisão e questões. Sábado permanece prática.</p></div></div><div class="plan-time-grid">${[1,2,3,4,5,6,0].map(d=>`<div class="day-time ${d===6?'special':''}"><label>${dayName(d)}</label><span class="day-input-label">Duração</span><input data-day-time="${d}" value="${minutesToClock(state.settings.dayMinutes[d]||0)}" inputmode="numeric" /><span class="day-input-label">Início</span><input class="start-time-input" type="time" data-day-start="${d}" value="${esc(state.settings.dayStartTimes?.[d]||'19:00')}" /></div>`).join('')}</div><div class="hero-stats" style="margin-top:14px"><div class="hero-stat"><small>Janela de conteúdo</small><strong>${minutesToClock(contentMins)}</strong></div><div class="hero-stat"><small>Aulas novas disponíveis</small><strong>${minutesToClock(lessonMins)}</strong></div><div class="hero-stat"><small>Prática agendada/sem</small><strong>${minutesToClock(practiceMin)}</strong></div><div class="hero-stat"><small>Margem não usada</small><strong>${minutesToClock(unused)}</strong></div></div></div>
  <div class="grid two" style="margin-top:16px"><div class="card"><div class="card-title"><div><h3>Prazo e viabilidade</h3><p>A capacidade até a prova respeita cada dia disponível e a reserva da reta final.</p></div><span class="badge ${analysis.insufficient?'high':'done'}">${analysis.insufficient?'Prioridade automática':'Análise'}</span></div><div class="timeline-summary"><div><small>Conclusão projetada</small><strong>${analysis.projectedDate?analysis.projectedDate.toLocaleDateString('pt-BR'):'—'}</strong></div><div><small>Semanas necessárias</small><strong>${Number.isFinite(analysis.weeksNeeded)?analysis.weeksNeeded.toFixed(1):'—'}</strong></div><div><small>Capacidade até a prova</small><strong>${analysis.capacityMinutes!==null?minutesToClock(analysis.capacityMinutes):'—'}</strong></div></div><p class="schedule-message ${analysis.insufficient?'risk':'ok'}">${statusText}</p><label class="toggle-row"><input type="checkbox" id="auto-priority" ${state.settings.autoPriority?'checked':''}><span>Ativar prioridade automática quando o prazo for insuficiente.</span></label>${analysis.insufficient?`<div class="priority-box"><strong>Ordem de prioridade pelo peso oficial de 2024</strong><p>${priority.map(s=>`${esc(s)} (${DATA.weights[s]} itens)`).join(' → ')}</p><small>O rateio passa a 75% peso da prova + 25% carga restante. Na reta final, os seus erros também reforçam a prioridade.</small></div>`:''}</div>
  <div class="card"><div class="card-title"><div><h3>Como ratear e encaixar aulas</h3><p>Equilibre carga restante, importância na prova e intervalos entre aulas.</p></div></div>${rangeControl('Carga restante do curso','loadWeight',state.settings.loadWeight)}${rangeControl('Peso da prova objetiva','examWeight',state.settings.examWeight)}<label class="field">Intervalo entre aulas (minutos)<input type="number" min="0" max="30" step="1" id="break-minutes" value="${Number(state.settings.breakMinutes??5)}"></label><p class="helper">Na reta final, o rateio de aulas é calculado somente sobre a parcela ainda destinada a conteúdo novo.</p></div></div>
  <div class="grid two" style="margin-top:16px"><div class="card"><div class="card-title"><div><h3>Sábado normal</h3><p>Distribuição usada fora da reta final.</p></div></div>${Object.entries(state.settings.saturday).map(([k,v])=>rangeControl(({revisao:'Revisão',questoes:'Questões',simulado:'Simulado',discursiva:'Discursiva / Atualidades'})[k],`sat-${k}`,v)).join('')}</div><div class="card"><div class="card-title"><div><h3>Reta final automática</h3><p>Nos 15 dias finais, o foco muda sem você precisar refazer o plano.</p></div><span class="badge ${sprint.active?'high':''}">${sprint.active?'Ativa':'Aguardando prova'}</span></div><div class="final-sprint-grid"><div><strong>60%</strong><span>dos dias de conteúdo para revisão + questões</span></div><div><strong>40%</strong><span>do sábado para revisão</span></div><div><strong>40%</strong><span>do sábado para questões</span></div><div><strong>15%</strong><span>do sábado para simulado</span></div></div><p class="helper">Revisões e questões usam primeiro os tópicos com maior número de erros registrados.</p></div></div>
  <div class="card" style="margin-top:16px"><div class="card-title"><div><h3>Rateio calculado</h3><p>${a[0]?.priorityMode?'Modo prioridade ativo: o peso da prova foi reforçado porque o prazo não comporta toda a carga.':sprint.active?'Reta final ativa: o percentual de erros por matéria também influencia o rateio.':'O cálculo diminui automaticamente as matérias conforme as aulas são concluídas.'}</p></div></div><div style="overflow:auto"><table class="allocation-table"><thead><tr><th>Matéria</th><th>Curso</th><th>Restante</th><th>Peso prova</th><th>Erros</th><th>Rateio</th><th>Meta aulas/sem</th><th>Estimativa</th></tr></thead><tbody>${a.map(x=>`<tr><td><strong>${esc(x.materia)}</strong></td><td>${secondsToClock(x.total)}</td><td>${secondsToClock(x.remaining)}</td><td>${x.items}/120</td><td>${pct(x.weakness||0,0)}</td><td>${pct(x.share,1)}</td><td class="time-value">${minutesToClock(x.weeklyMinutes)}</td><td>${x.weeks?`${x.weeks.toFixed(1)} sem`:'Concluído'}</td></tr>`).join('')}</tbody></table></div></div>
  <div class="card" style="margin-top:16px"><div class="card-title"><div><h3>Ciclo sugerido</h3><p>O rateio define quais matérias precisam de mais tempo; dentro de cada matéria, o calendário pega a próxima aula pendente em ordem.</p></div></div><div class="cycle-grid">${state.settings.cycle.map((x,i)=>`<div class="task"><span class="badge">${i+1}</span><strong>${esc(x)}</strong><span class="task-time">${minutesToClock(a.find(y=>y.materia===x)?.weeklyMinutes||0)}</span></div>`).join('')}</div></div></div>`;
  $$('[data-day-time]').forEach(inp=>inp.addEventListener('change',()=>{const m=clockToMinutes(inp.value);if(Number.isNaN(m)){toast('Use o formato 1:20 para uma hora e vinte minutos.','error');inp.value=minutesToClock(state.settings.dayMinutes[inp.dataset.dayTime]||0);return}state.settings.dayMinutes[inp.dataset.dayTime]=m;invalidateWeeklyPlans();renderPlan()}));
  $$('[data-day-start]').forEach(inp=>inp.addEventListener('change',()=>{state.settings.dayStartTimes[inp.dataset.dayStart]=inp.value||'19:00';invalidateWeeklyPlans();renderPlan()}));
  $('#break-minutes').onchange=e=>{state.settings.breakMinutes=clamp(Number(e.target.value||0),0,30);invalidateWeeklyPlans();renderPlan()};
  $('#prep-mode').onchange=e=>{state.settings.preparationMode=e.target.value==='post'?'post':'pre';invalidateWeeklyPlans();renderPlan()};
  $('#study-start-date').onchange=e=>{state.settings.studyStartDate=e.target.value;invalidateWeeklyPlans();renderPlan()};
  $('#edital-date').onchange=e=>{state.settings.editalDate=e.target.value;invalidateWeeklyPlans();renderPlan()};
  $('#objective-exam-date').onchange=e=>{state.settings.objectiveExamDate=e.target.value;state.settings.targetDate=e.target.value;invalidateWeeklyPlans();renderPlan()};
  $('#auto-priority').onchange=e=>{state.settings.autoPriority=e.target.checked;invalidateWeeklyPlans();renderPlan()};
  $$('[data-range]').forEach(inp=>{inp.oninput=()=>{$(`[data-range-label="${inp.dataset.range}"]`).textContent=pct(Number(inp.value)/100)};inp.onchange=()=>{const val=Number(inp.value)/100,key=inp.dataset.range;if(key.startsWith('sat-'))state.settings.saturday[key.slice(4)]=val;else state.settings[key]=val;invalidateWeeklyPlans();renderPlan()}})
}
function rangeControl(label,key,value){return`<div class="range-row"><label>${label}<div class="progress" style="margin-top:7px"><i style="width:${pct(value)}"></i></div></label><div><input type="range" min="0" max="100" step="5" value="${Math.round(value*100)}" data-range="${key}" style="width:100%"><strong data-range-label="${key}" style="display:block;text-align:center;margin-top:3px">${pct(value)}</strong></div></div>`}

function matterHue(name=''){let h=0;for(const c of String(name))h=(h*31+c.charCodeAt(0))%360;return h}
function calendarEventHTML(e,minMinute,pxPerMinute){
  const top=(e.startMinute-minMinute)*pxPerMinute,height=Math.max(34,(e.endMinute-e.startMinute)*pxPerMinute-3),done=eventDone(e),hue=matterHue(e.materia);
  if(e.type==='lesson')return `<button class="calendar-event lesson ${done?'done':''}" data-calendar-lesson="${e.lessonId}" style="top:${top}px;height:${height}px;--event-hue:${hue}"><span class="calendar-event-time">${formatTimeOfDay(e.startMinute)}–${formatTimeOfDay(e.endMinute)}</span><strong>${esc(e.materia)}</strong><small>Tópico ${esc(e.topico)} · Aula ${esc(e.numero)} ${done?'· ✓ Assistida':''}</small><span class="calendar-event-title">${esc(e.titulo)}</span></button>`;
  return `<button class="calendar-event practice ${done?'done':''}" data-calendar-practice="${esc(e.route||'hoje')}" data-calendar-subject="${esc(e.subject||'')}" data-calendar-topic="${esc(e.topicId||'')}" style="top:${top}px;height:${height}px"><span class="calendar-event-time">${formatTimeOfDay(e.startMinute)}–${formatTimeOfDay(e.endMinute)}</span><strong>${esc(e.materia)}</strong><small>${done?'✓ Concluído':e.smart?'Priorizado pelos seus erros':'Bloco de prática'}</small><span class="calendar-event-title">${esc(e.titulo||'')}</span></button>`
}
function renderCalendar(){
  const base=planBaseDate(calendarWeekOffset),plan=getWeeklyPlan(base),weekStart=startOfWeek(base),dayOrder=[1,2,3,4,5,6,0];
  const days=dayOrder.map(d=>{const date=dateFromWeekDay(weekStart,d);return{day:d,date,iso:localDateISO(date),events:eventsForDate(plan,localDateISO(date))}});
  const all=plan.events||[],allStarts=all.map(e=>e.startMinute),allEnds=all.map(e=>e.endMinute);let minMinute=allStarts.length?Math.floor(Math.min(...allStarts)/60)*60:8*60,maxMinute=allEnds.length?Math.ceil(Math.max(...allEnds)/60)*60:22*60;
  if(maxMinute-minMinute<300)maxMinute=minMinute+300;maxMinute=Math.min(maxMinute,24*60);const pxPerMinute=1.25,totalHeight=(maxMinute-minMinute)*pxPerMinute;
  const rangeLabel=`${dateBR(days[0].iso)} – ${dateBR(days[6].iso)}`,isCurrent=weekKey(base)===weekKey(new Date()),now=new Date(),nowMinute=now.getHours()*60+now.getMinutes();
  const hourLabels=[];for(let m=minMinute;m<=maxMinute;m+=60)hourLabels.push(`<span style="top:${(m-minMinute)*pxPerMinute}px">${String(Math.floor(m/60)).padStart(2,'0')}:00</span>`);
  const headers=days.map(x=>`<div class="calendar-day-head ${x.iso===isoDate()?'today':''}"><strong>${new Intl.DateTimeFormat('pt-BR',{weekday:'short'}).format(x.date).replace('.','')}</strong><span>${String(x.date.getDate()).padStart(2,'0')}</span><small>${minutesToClock(Number(state.settings.dayMinutes[x.day]||0))}</small></div>`).join('');
  const columns=days.map(x=>{const currentLine=isCurrent&&x.iso===isoDate()&&nowMinute>=minMinute&&nowMinute<=maxMinute?`<div class="calendar-now-line" style="top:${(nowMinute-minMinute)*pxPerMinute}px"><i></i></div>`:'';return `<div class="calendar-day-column" data-calendar-date="${x.iso}" style="height:${totalHeight}px">${currentLine}${x.events.map(e=>calendarEventHTML(e,minMinute,pxPerMinute)).join('')}${!x.events.length?'<div class="calendar-no-events">Sem agenda</div>':''}</div>`}).join('');
  const totalLessons=all.filter(e=>e.type==='lesson').length,totalStudy=all.filter(e=>e.type==='lesson').reduce((n,e)=>n+e.endMinute-e.startMinute,0),totalPractice=all.filter(e=>e.type==='practice').reduce((n,e)=>n+e.endMinute-e.startMinute,0),unused=Object.values(plan.unusedByDay||{}).reduce((a,b)=>a+Number(b||0),0);
  view.innerHTML=`<div class="fade-in"><div class="section-head"><div><h2>Calendário semanal de estudos</h2><p>Agenda gerada com a aula exata, duração real e horário de início/fim.</p></div><span class="badge">${rangeLabel}</span></div>
  <div class="calendar-toolbar card"><div class="calendar-nav"><button class="secondary" id="calendar-prev">←</button><button class="secondary" id="calendar-today">Hoje</button><button class="secondary" id="calendar-next">→</button></div><div class="calendar-toolbar-stats"><span><strong>${totalLessons}</strong> aulas</span><span><strong>${minutesToClock(totalStudy)}</strong> aulas</span><span><strong>${minutesToClock(totalPractice)}</strong> prática</span><span><strong>${minutesToClock(unused)}</strong> margem</span></div><button class="primary" id="calendar-recalc">Recalcular semana</button></div>
  <div class="calendar-info"><span>💡 Clique em uma aula para abrir exatamente essa aula dentro do seu painel. Se você cadastrar o link direto do Gran, também poderá abri-la externamente.</span></div>
  <div class="calendar-scroll"><div class="calendar-week"><div class="calendar-corner">Hora</div>${headers}<div class="calendar-time-axis" style="height:${totalHeight}px">${hourLabels.join('')}</div>${columns}</div></div>
  <div class="card calendar-list-card"><div class="card-title"><div><h3>Agenda da semana em lista</h3><p>Útil principalmente no celular.</p></div></div><div class="calendar-agenda-list">${days.map(x=>`<section><h4>${dayName(x.day)} · ${dateBR(x.iso)}</h4>${x.events.map(scheduleEventTask).join('')||'<div class="empty mini">Sem atividades.</div>'}</section>`).join('')}</div></div></div>`;
  $('#calendar-prev').onclick=()=>{calendarWeekOffset--;renderCalendar()};$('#calendar-next').onclick=()=>{calendarWeekOffset++;renderCalendar()};$('#calendar-today').onclick=()=>{calendarWeekOffset=0;renderCalendar()};$('#calendar-recalc').onclick=()=>{getWeeklyPlan(base,true);toast('Semana recalculada com as aulas pendentes atuais.');renderCalendar()};
  $$('[data-calendar-lesson]').forEach(el=>el.onclick=()=>openLesson(el.dataset.calendarLesson));$$('[data-calendar-practice]').forEach(el=>el.onclick=()=>{if(el.dataset.calendarPractice==='questoes')questionPrefill={subject:el.dataset.calendarSubject||'',topicId:el.dataset.calendarTopic||''};navigate(el.dataset.calendarPractice)});bindScheduleTasks(all,renderCalendar)
}

function renderEdital(){
  const subjects=['Todas',...new Set(DATA.edital.map(x=>x.materia))];const pageSize=Number(state.settings.editalPageSize||30);
  view.innerHTML=`<div class="fade-in"><div class="section-head"><div><h2>Edital verticalizado</h2><p>${DATA.edital.length} tópicos da base 2024. Marque o que concluir e registre questões.</p></div><span class="badge">Base: ${esc(DATA.metadata.baseEdital)}</span></div>
  <div class="filters"><input id="edital-search" placeholder="Buscar conteúdo, item ou matéria…"><select id="edital-subject">${subjects.map(s=>`<option>${esc(s)}</option>`).join('')}</select><select id="edital-status"><option value="all">Todos</option><option value="pending">Pendentes</option><option value="done">Concluídos</option><option value="review">Revisar</option></select></div><div id="edital-results" style="margin-top:14px"></div></div>`;
  const draw=()=>{const q=normalizeText($('#edital-search').value),sub=$('#edital-subject').value,st=$('#edital-status').value;let arr=DATA.edital.filter(x=>(sub==='Todas'||x.materia===sub)&&(!q||normalizeText(`${x.materia} ${x.item} ${x.conteudo}`).includes(q)));arr=arr.filter(x=>{const s=statusEdital(x.id);return st==='all'||(st==='done'&&s.done)||(st==='pending'&&!s.done)||(st==='review'&&s.review)});const pages=Math.max(1,Math.ceil(arr.length/pageSize));editalPage=clamp(editalPage,1,pages);const slice=arr.slice((editalPage-1)*pageSize,editalPage*pageSize);$('#edital-results').innerHTML=`<div class="data-list">${slice.map(renderEditalItem).join('')||'<div class="empty"><strong>Nenhum tópico encontrado</strong>Ajuste os filtros.</div>'}</div>${pager(editalPage,pages,'edital')}`;bindEditalItems();bindPager('edital',p=>{editalPage=p;draw()})};
  $('#edital-search').oninput=debounce(()=>{editalPage=1;draw()},120);$('#edital-subject').onchange=$('#edital-status').onchange=()=>{editalPage=1;draw()};draw()
}
function renderEditalItem(x){const s=statusEdital(x.id),acc=s.questions?Number(s.correct||0)/Number(s.questions):0;return`<article class="item-card ${s.done?'done':''}" data-edital-id="${x.id}"><div class="item-top"><div class="item-main"><span class="eyebrow">${esc(x.materia)} · Item ${esc(x.item)}</span><h4>${esc(x.conteudo)}</h4><div class="item-meta"><span class="badge ${x.prioridade==='Alto'?'high':''}">${esc(x.prioridade)}</span><span class="badge">Peso ${Number(x.pesoTopico).toFixed(2)}</span>${s.questions?`<span class="badge">Acerto ${pct(acc,0)}</span>`:''}${s.completedAt?`<span class="badge done">${dateBR(s.completedAt)}</span>`:''}</div></div><div class="item-actions"><button class="check-btn ${s.done?'on':''}" data-action="done" title="Concluído">✓</button><button class="check-btn review-btn ${s.review?'on':''}" data-action="review" title="Revisar">↻</button></div></div><div class="item-actions" style="margin-top:12px"><label class="field">Questões<input class="mini-input" type="number" min="0" data-q="questions" value="${Number(s.questions||0)}"></label><label class="field">Acertos<input class="mini-input" type="number" min="0" data-q="correct" value="${Number(s.correct||0)}"></label></div></article>`}
function bindEditalItems(){$$('[data-edital-id]').forEach(card=>{const id=card.dataset.editalId;card.querySelector('[data-action="done"]').onclick=()=>{const s=statusEdital(id),done=!s.done;state.edital[id]={...s,done,completedAt:done?(s.completedAt||isoDate()):null};save();renderEdital()};card.querySelector('[data-action="review"]').onclick=()=>{const s=statusEdital(id);state.edital[id]={...s,review:!s.review};save();renderEdital()};$$('[data-q]',card).forEach(inp=>inp.onchange=()=>{const s=statusEdital(id);state.edital[id]={...s,[inp.dataset.q]:Math.max(0,Number(inp.value||0))};if(state.edital[id].correct>state.edital[id].questions)state.edital[id].correct=state.edital[id].questions;invalidateWeeklyPlans();toast('Desempenho atualizado e revisões recalculadas.')})})}

function renderCourse(){
  const subjects=['Todas',...new Set(DATA.course.map(x=>x.materia))],pageSize=Number(state.settings.coursePageSize||40),focus=courseFocusId?DATA.course.find(x=>x.id===courseFocusId):null;
  const focusHTML=focus?`<div class="focus-lesson-wrap" data-focus-lesson><div class="card-title"><div><span class="eyebrow">Aula selecionada pelo calendário</span><h3>Próxima aula planejada</h3></div><button class="secondary" id="clear-course-focus">Fechar destaque</button></div>${renderLesson(focus,true)}<div class="focus-lesson-actions">${state.lessonLinks?.[focus.id]?`<button class="primary" id="open-direct-link">Abrir direto no Gran ↗</button><button class="secondary" id="edit-direct-link">Editar link</button>`:`<button class="primary" id="set-direct-link">Cadastrar link direto do Gran</button>`}<span class="helper">A base enviada não contém URLs privadas das aulas. Cadastre o link uma vez para abrir esta aula diretamente no Gran depois.</span></div></div>`:'';
  view.innerHTML=`<div class="fade-in"><div class="section-head"><div><h2>Curso Gran</h2><p>${DATA.course.length} videoaulas · ${secondsToClock(DATA.course.reduce((a,x)=>a+x.duracaoSegundos,0))} extraídas da grade.</p></div><span class="badge">Código ${esc(DATA.metadata.codigoCurso)}</span></div>${focusHTML}
  <div class="filters"><input id="course-search" placeholder="Buscar aula, professor ou tópico…"><select id="course-subject">${subjects.map(s=>`<option>${esc(s)}</option>`).join('')}</select><select id="course-status"><option value="all">Todas</option><option value="pending">Não assistidas</option><option value="done">Assistidas</option><option value="review">Revisar</option></select></div><div id="course-results" style="margin-top:14px"></div></div>`;
  const draw=()=>{const q=normalizeText($('#course-search').value),sub=$('#course-subject').value,st=$('#course-status').value;let arr=DATA.course.filter(x=>(sub==='Todas'||x.materia===sub)&&(!q||normalizeText(`${x.materia} ${x.titulo} ${x.professor} ${x.conteudoTopico}`).includes(q)));arr=arr.filter(x=>{const s=statusCourse(x.id);return st==='all'||(st==='done'&&s.watched)||(st==='pending'&&!s.watched)||(st==='review'&&s.review)});const pages=Math.max(1,Math.ceil(arr.length/pageSize));coursePage=clamp(coursePage,1,pages);const slice=arr.slice((coursePage-1)*pageSize,coursePage*pageSize);$('#course-results').innerHTML=`<div class="data-list">${slice.map(x=>renderLesson(x,false)).join('')||'<div class="empty"><strong>Nenhuma aula encontrada</strong>Ajuste os filtros.</div>'}</div>${pager(coursePage,pages,'course')}`;bindLessons();bindPager('course',p=>{coursePage=p;draw()})};
  $('#course-search').oninput=debounce(()=>{coursePage=1;draw()},120);$('#course-subject').onchange=$('#course-status').onchange=()=>{coursePage=1;draw()};draw();
  if(focus){$('#clear-course-focus').onclick=()=>{courseFocusId=null;renderCourse()};const set=$('#set-direct-link'),edit=$('#edit-direct-link'),open=$('#open-direct-link');if(set)set.onclick=()=>setLessonLink(focus.id);if(edit)edit.onclick=()=>setLessonLink(focus.id);if(open)open.onclick=()=>openLesson(focus.id,true)}
}
function renderLesson(x,focused=false){const s=statusCourse(x.id);return`<article class="item-card lesson-card ${s.watched?'done':''} ${focused?'focused':''}" data-course-id="${x.id}"><div class="item-top"><div class="item-main"><span class="eyebrow">${esc(x.materia)} · Tópico ${esc(x.topico)} · Aula ${esc(x.numero)}</span><h4>${esc(x.titulo)}</h4><p>${esc(x.professor||'Professor não informado')}</p><div class="item-meta"><span class="badge lesson-duration">${x.duracao?secondsToClock(x.duracaoSegundos):'—'}</span>${s.completedAt?`<span class="badge done">Assistida em ${dateBR(s.completedAt)}</span>`:''}${state.lessonLinks?.[x.id]?'<span class="badge done">Link Gran salvo</span>':''}</div></div><div class="item-actions"><button class="check-btn ${s.watched?'on':''}" data-action="watched" title="Assistida">✓</button><button class="check-btn review-btn ${s.review?'on':''}" data-action="review" title="Revisar">↻</button></div></div></article>`}
function bindLessons(){$$('[data-course-id]').forEach(card=>{const id=card.dataset.courseId;card.querySelector('[data-action="watched"]').onclick=()=>{const s=statusCourse(id),watched=!s.watched;state.course[id]={...s,watched,completedAt:watched?(s.completedAt||isoDate()):null};invalidateWeeklyPlans();if(courseFocusId===id)renderCourse();else renderCourse()};card.querySelector('[data-action="review"]').onclick=()=>{const s=statusCourse(id);state.course[id]={...s,review:!s.review};save();renderCourse()}})}
function pager(page,pages,key){if(pages<=1)return'';return`<div class="pagination"><button data-page="prev" data-pager="${key}" ${page===1?'disabled':''}>←</button><span>Página ${page} de ${pages}</span><button data-page="next" data-pager="${key}" ${page===pages?'disabled':''}>→</button></div>`}
function bindPager(key,cb){$$(`[data-pager="${key}"]`).forEach(b=>b.onclick=()=>cb(b.dataset.page==='prev'?(key==='course'?coursePage:editalPage)-1:(key==='course'?coursePage:editalPage)+1))}

function renderQuestions(){
  const subjects=objectiveSubjects(),qa=questionAnalytics(),subjectRows=qa.subjects.filter(x=>x.questions>0).sort((a,b)=>b.errors-a.errors||b.questions-a.questions);
  view.innerHTML=`<div class="fade-in"><div class="section-head"><div><h2>Controle e inteligência de questões</h2><p>Registre matéria e tópico. O sistema monitora volume, acertos, erros e transforma os piores tópicos em revisões sugeridas.</p></div><span class="badge">${fmtNumber(qa.totalQuestions)} questões</span></div>
  <div class="card"><form id="question-form" class="question-form smart-question-form"><label class="field">Data<input type="date" name="date" value="${isoDate()}"></label><label class="field">Matéria<select name="subject">${subjects.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select></label><label class="field wide">Tópico do edital<select name="topicId" id="question-topic"></select></label><label class="field">Questões<input type="number" min="1" name="questions" required></label><label class="field">Acertos<input type="number" min="0" name="correct" required></label><label class="field wide">Observação<input name="note" placeholder="Ex.: Cebraspe, simulado, revisão de microsserviços…"></label><button class="primary" type="submit">Salvar bloco</button></form></div>
  <div class="grid kpis" style="margin-top:16px">${kpi('Questões',fmtNumber(qa.totalQuestions),`${fmtNumber(qa.recent7)} nos últimos 7 dias`,'☷')}${kpi('Acertos',fmtNumber(qa.totalCorrect),`${fmtNumber(qa.totalErrors)} erros acumulados`,'✓')}${kpi('Precisão',pct(qa.accuracy,1),`${fmtNumber(qa.recent15)} questões em 15 dias`,'◎')}${kpi('Mais erros',qa.mostErrors?shortMatter(qa.mostErrors.subject):'—',qa.mostErrors?`${qa.mostErrors.errors} erros · ${pct(qa.mostErrors.errorRate,0)}`:'Sem dados','!')}</div>
  <div class="grid two"><div class="card"><div class="card-title"><div><h3>Desempenho por matéria</h3><p>Ordenado inicialmente pela quantidade de erros.</p></div><span class="badge">${subjectRows.length} matérias com dados</span></div><div style="overflow:auto"><table class="performance-table"><thead><tr><th>Matéria</th><th>Questões</th><th>Acertos</th><th>Erros</th><th>% acerto</th><th>% erro</th></tr></thead><tbody>${subjectRows.map(x=>`<tr><td><strong>${esc(x.subject)}</strong></td><td>${x.questions}</td><td class="good-number">${x.correct}</td><td class="bad-number">${x.errors}</td><td>${pct(x.accuracy,0)}</td><td>${pct(x.errorRate,0)}</td></tr>`).join('')||'<tr><td colspan="6">Nenhuma questão registrada ainda.</td></tr>'}</tbody></table></div></div>
  <div class="card"><div class="card-title"><div><h3>Revisões sugeridas pelos erros</h3><p>Quanto mais erros e maior o peso da matéria, maior a prioridade.</p></div><span class="badge review">${qa.recommendations.length}</span></div><div class="data-list">${qa.recommendations.slice(0,8).map((x,i)=>`<div class="smart-review-card"><span class="rank">${i+1}</span><div><strong>${esc(x.subject)} · Item ${esc(x.item)}</strong><small>${esc(x.label)}</small><div class="item-meta"><span class="badge high">${x.errors} erros</span><span class="badge">${x.questions} questões</span><span class="badge">${pct(x.accuracy,0)} acerto</span></div></div><button class="secondary" data-add-smart-review="${x.topicId}">${statusEdital(x.topicId).review?'Na revisão':'Revisar'}</button></div>`).join('')||'<div class="empty mini">Registre questões ligadas a tópicos do edital para gerar recomendações automáticas.</div>'}</div></div></div>
  <div class="card" style="margin-top:16px"><div class="card-title"><div><h3>Histórico de blocos</h3><p>Os registros com data alimentam as métricas de 7, 15 e 30 dias.</p></div></div><div style="overflow:auto"><table class="history-table"><thead><tr><th>Data</th><th>Matéria</th><th>Tópico</th><th>Questões</th><th>Acertos</th><th>Erros</th><th>%</th><th>Observação</th><th></th></tr></thead><tbody>${state.questions.slice().reverse().map(q=>`<tr><td>${dateBR(q.date)}</td><td>${esc(q.subject)}</td><td>${esc(q.topicLabel||'Geral da matéria')}</td><td>${q.questions}</td><td>${q.correct}</td><td>${Math.max(0,Number(q.questions)-Number(q.correct))}</td><td>${pct(q.correct/q.questions,0)}</td><td>${esc(q.note||'')}</td><td><button class="danger ghost" data-delete-q="${q.id}">Excluir</button></td></tr>`).join('')||'<tr><td colspan="9">Nenhum bloco registrado.</td></tr>'}</tbody></table></div></div></div>`;
  const subjectSel=$('[name="subject"]'),topicSel=$('#question-topic');
  const fillTopics=(preferred='')=>{const list=DATA.edital.filter(x=>x.materia===subjectSel.value);topicSel.innerHTML=`<option value="">Geral da matéria</option>${list.map(x=>`<option value="${x.id}">Item ${esc(x.item)} · ${esc(x.conteudo)}</option>`).join('')}`;if(preferred&&[...topicSel.options].some(o=>o.value===preferred))topicSel.value=preferred};
  if(questionPrefill?.subject&&subjects.includes(questionPrefill.subject))subjectSel.value=questionPrefill.subject;fillTopics(questionPrefill?.topicId||'');questionPrefill=null;subjectSel.onchange=()=>fillTopics('');
  $('#question-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),questions=Math.max(1,Number(f.get('questions'))),correct=clamp(Number(f.get('correct')),0,questions),topicId=f.get('topicId')||null,item=topicId?DATA.edital.find(x=>x.id===topicId):null;state.questions.push({id:uid('q'),date:f.get('date'),subject:f.get('subject'),topicId,topicLabel:item?`Item ${item.item} · ${item.conteudo}`:'Geral da matéria',questions,correct,note:f.get('note'),createdAt:new Date().toISOString()});invalidateWeeklyPlans();toast('Bloco salvo e diagnóstico recalculado.');renderQuestions()};
  $$('[data-delete-q]').forEach(b=>b.onclick=()=>{state.questions=state.questions.filter(q=>q.id!==b.dataset.deleteQ);invalidateWeeklyPlans();renderQuestions()});
  $$('[data-add-smart-review]').forEach(b=>b.onclick=()=>{const id=b.dataset.addSmartReview,st=statusEdital(id);state.edital[id]={...st,review:true};invalidateWeeklyPlans();toast('Tópico adicionado à fila de revisão.');renderQuestions()})
}
function renderReviews(){
  const edit=DATA.edital.filter(x=>statusEdital(x.id).review),less=DATA.course.filter(x=>statusCourse(x.id).review),qa=questionAnalytics(),smart=qa.recommendations;
  view.innerHTML=`<div class="fade-in"><div class="section-head"><div><h2>Fila de revisões</h2><p>Revisões manuais + sugestões automáticas com base nos tópicos em que você mais erra.</p></div><span class="badge review">${edit.length+less.length} marcadas · ${smart.length} sugeridas</span></div>
  <div class="card smart-review-section"><div class="card-title"><div><h3>Revisão inteligente por erros</h3><p>Prioridade calculada por número de erros, taxa de erro e peso da matéria na prova objetiva de 2024.</p></div><span class="badge high">Automático</span></div><div class="smart-review-grid">${smart.map((x,i)=>`<article class="smart-review-card"><span class="rank">${i+1}</span><div><strong>${esc(x.subject)} · Item ${esc(x.item)}</strong><small>${esc(x.label)}</small><div class="item-meta"><span class="badge high">${x.errors} erros</span><span class="badge">${pct(x.errorRate,0)} de erro</span><span class="badge">peso ${x.weight}/120</span></div></div><button class="secondary" data-add-smart-review="${x.topicId}">${statusEdital(x.topicId).review?'Já marcado':'Adicionar'}</button></article>`).join('')||'<div class="empty mini">Ainda não há erros por tópico suficientes para montar uma fila inteligente.</div>'}</div></div>
  <div class="grid two" style="margin-top:16px"><div class="card"><div class="card-title"><div><h3>Edital</h3><p>${edit.length} tópicos marcados para revisão.</p></div></div><div class="data-list">${edit.map(x=>{const perf=qa.topics.find(t=>t.topicId===x.id);return`<div class="task"><div><strong>${esc(x.materia)} · Item ${esc(x.item)}</strong><small style="display:block;color:var(--muted)">${esc(x.conteudo)}</small>${perf?`<span class="badge high" style="margin-top:6px">${perf.errors} erros · ${pct(perf.accuracy,0)} acerto</span>`:''}</div><button class="secondary" data-review-edital="${x.id}">Revisado</button></div>`}).join('')||'<div class="empty">Nenhum tópico marcado.</div>'}</div></div><div class="card"><div class="card-title"><div><h3>Videoaulas</h3><p>${less.length} aulas marcadas.</p></div></div><div class="data-list">${less.map(x=>`<div class="task"><div><strong>${esc(x.titulo)}</strong><small style="display:block;color:var(--muted)">${esc(x.materia)} · ${esc(x.professor)}</small></div><button class="secondary" data-review-course="${x.id}">Revisada</button></div>`).join('')||'<div class="empty">Nenhuma aula marcada.</div>'}</div></div></div></div>`;
  $$('[data-review-edital]').forEach(b=>b.onclick=()=>{state.edital[b.dataset.reviewEdital]={...statusEdital(b.dataset.reviewEdital),review:false};invalidateWeeklyPlans();renderReviews()});
  $$('[data-review-course]').forEach(b=>b.onclick=()=>{state.course[b.dataset.reviewCourse]={...statusCourse(b.dataset.reviewCourse),review:false};save();renderReviews()});
  $$('[data-add-smart-review]').forEach(b=>b.onclick=()=>{const id=b.dataset.addSmartReview;state.edital[id]={...statusEdital(id),review:true};invalidateWeeklyPlans();toast('Tópico adicionado à revisão.');renderReviews()})
}
function discPair(id){return DATA.discursivas.find(x=>x.id===Number(id))||DATA.discursivas[0]}
function chooseDiscursive(kind='pair'){
  const all=DATA.discursivas,random=()=>all[Math.floor(Math.random()*all.length)].id;if(kind==='pair'){const id=random();state.discursiva.pairId=id;state.discursiva.atualidadeId=id;state.discursiva.tiId=id;}else if(kind==='atualidade')state.discursiva.atualidadeId=random();else state.discursiva.tiId=random();save();renderDiscursive();
}
function renderDiscursive(){
  if(!state.discursiva.pairId){state.discursiva.pairId=1;state.discursiva.atualidadeId=1;state.discursiva.tiId=1}
  const a=discPair(state.discursiva.atualidadeId),t=discPair(state.discursiva.tiId),sessions=state.discursiveSessions||[];
  view.innerHTML=`<div class="fade-in"><div class="section-head"><div><h2>Treino de prova discursiva</h2><p>100 pares preparados: um tema de Atualidades (P3) e um tema técnico de TI (P4).</p></div><span class="badge">${DATA.discursivas.length} pares</span></div>
  <div class="discursive-actions"><button class="primary" id="draw-pair">Sortear par completo</button><button class="secondary" id="draw-current">Sortear Atualidades</button><button class="secondary" id="draw-ti">Sortear TI</button></div>
  <div class="grid two" style="margin-top:16px"><article class="card prompt-card current"><span class="eyebrow">P3 · Atualidades · até 40 linhas</span><h3>Tema sorteado</h3><p>${esc(a.atualidade)}</p><div class="prompt-number">Tema #${a.id}</div></article><article class="card prompt-card tech"><span class="eyebrow">P4 · TI · situação-problema · até 80 linhas</span><h3>Tema sorteado</h3><p>${esc(t.ti)}</p><div class="prompt-number">Tema #${t.id}</div></article></div>
  <div class="card" style="margin-top:16px"><div class="card-title"><div><h3>Área de rascunho</h3><p>Use para estruturar tese, tópicos técnicos, riscos, solução e conclusão. O texto fica somente nesta sessão até ser registrado.</p></div><span class="badge" id="draft-count">0 palavras</span></div><textarea id="discursive-draft" class="discursive-textarea" placeholder="Escreva seu rascunho ou estrutura de resposta aqui..."></textarea><div class="hero-actions"><button class="primary" id="save-discursive">Registrar treino</button><button class="secondary" id="copy-prompts">Copiar temas</button></div></div>
  <div class="card" style="margin-top:16px"><div class="card-title"><div><h3>Histórico de treinos</h3><p>Registros salvos no navegador.</p></div><span class="badge">${sessions.length}</span></div>${sessions.slice().reverse().slice(0,12).map(x=>`<div class="task"><div><strong>${dateBR(x.date)} · Atualidades #${x.atualidadeId} + TI #${x.tiId}</strong><small style="display:block;color:var(--muted)">${x.words} palavras · ${esc(x.note||'treino registrado')}</small></div></div>`).join('')||'<div class="empty">Nenhum treino registrado.</div>'}</div></div>`;
  $('#draw-pair').onclick=()=>chooseDiscursive('pair');$('#draw-current').onclick=()=>chooseDiscursive('atualidade');$('#draw-ti').onclick=()=>chooseDiscursive('ti');
  const draft=$('#discursive-draft'),count=()=>{$('#draft-count').textContent=`${draft.value.trim()?draft.value.trim().split(/\s+/).length:0} palavras`};draft.oninput=count;
  $('#save-discursive').onclick=()=>{const words=draft.value.trim()?draft.value.trim().split(/\s+/).length:0;state.discursiveSessions.push({id:uid('disc'),date:isoDate(),atualidadeId:a.id,tiId:t.id,words,note:draft.value.trim().slice(0,180),createdAt:new Date().toISOString()});state.discursiva.history.push({atualidadeId:a.id,tiId:t.id,date:isoDate()});save();toast('Treino discursivo registrado.');renderDiscursive()};
  $('#copy-prompts').onclick=async()=>{const txt=`ATUALIDADES: ${a.atualidade}\n\nTI: ${t.ti}`;try{await navigator.clipboard.writeText(txt);toast('Temas copiados.')}catch{toast('Não foi possível copiar automaticamente.','error')}}
}

function renderCoverage(){
  const video=DATA.coverage.filter(x=>x.modalidade==='Videoaula'),pdf=DATA.coverage.filter(x=>x.modalidade==='PDF');view.innerHTML=`<div class="fade-in"><div class="section-head"><div><h2>Cobertura do curso</h2><p>Lacunas declaradas na grade enviada. Use esta tela para não confundir “tem aula” com “está no edital”.</p></div><span class="badge high">Atenção</span></div><div class="grid two"><div class="card"><div class="card-title"><div><h3>Não ministrado em videoaula</h3><p>${video.length} registros.</p></div></div><div class="coverage-grid">${video.map(gap).join('')}</div></div><div class="card"><div class="card-title"><div><h3>Não ministrado em PDF</h3><p>${pdf.length} registros consolidados.</p></div></div><div class="coverage-grid">${pdf.map(gap).join('')}</div></div></div></div>`
}
function gap(x){return`<div class="gap-card"><span class="badge high">${esc(x.materia)}</span><h4>${esc(x.modalidade)}</h4><p>${esc(x.conteudo)}</p><small>${esc(x.acao)}</small></div>`}

function renderConfig(){
  const notif=state.settings.notifications||{},support='Notification' in window?Notification.permission:'indisponível';
  view.innerHTML=`<div class="fade-in"><div class="section-head"><div><h2>Configurações e backup</h2><p>Seu progresso fica no navegador. Exporte backups periodicamente.</p></div><span class="badge">Atualizado ${dateBR(DATA.metadata.updatedAt)}</span></div><div class="settings-grid">
  <div class="card"><div class="card-title"><div><h3>Aparência</h3><p>Tema preferido do aplicativo.</p></div></div><button class="secondary" id="settings-theme">Usar tema ${state.settings.theme==='dark'?'claro':'escuro'}</button></div>
  <div class="card"><div class="card-title"><div><h3>Lembretes motivacionais</h3><p>500 frases na base. O site tenta avisar após um período de inatividade.</p></div><span class="badge">${DATA.phrases.length} frases</span></div><label class="field">Considerar inatividade após<input type="number" min="1" max="336" id="inactive-hours" value="${Number(notif.inactivityHours||24)}"></label><div class="hero-actions"><button class="primary" id="enable-notifications">${notif.enabled?'Notificações ativadas':'Ativar notificações'}</button><button class="secondary" id="test-phrase">Mostrar frase</button></div><p class="helper">Permissão do navegador: ${esc(support)}. Em GitHub Pages, lembretes com o site completamente fechado dependem do suporte do navegador a PWA/Periodic Background Sync; sem esse suporte não há garantia de entrega sem um serviço de push.</p></div>
  <div class="card"><div class="card-title"><div><h3>Backup</h3><p>Leve seu progresso para outro navegador ou dispositivo.</p></div></div><div class="hero-actions"><button class="primary" id="export-backup">Exportar JSON</button><button class="secondary" id="open-import">Importar JSON</button></div></div>
  <div class="card"><div class="card-title"><div><h3>Base do projeto</h3><p>Informações carregadas nos JSONs.</p></div></div><div class="progress-row"><div><span>Edital</span><span>${DATA.edital.length} tópicos</span></div></div><div class="progress-row"><div><span>Curso Gran</span><span>${DATA.course.length} aulas</span></div></div><div class="progress-row"><div><span>Frases</span><span>${DATA.phrases.length}</span></div></div><div class="progress-row"><div><span>Pares discursiva</span><span>${DATA.discursivas.length}</span></div></div><div class="progress-row"><div><span>Carga extraída</span><span>${secondsToClock(DATA.metadata.cargaExtraidaSegundos)}</span></div></div><div class="progress-row"><div><span>Base</span><span>${esc(DATA.metadata.baseEdital)}</span></div></div><div class="progress-row"><div><span>Fase</span><span>${preparationLabel()}</span></div></div><div class="progress-row"><div><span>Início considerado</span><span>${dateBR(preparationReferenceDate())}</span></div></div><div class="progress-row"><div><span>1ª prova objetiva</span><span>${dateBR(examDateValue())}</span></div></div></div>
  <div class="card danger-zone"><div class="card-title"><div><h3>Apagar progresso</h3><p>Restaura o site para os dados iniciais. Faça backup antes.</p></div></div><button class="danger" id="reset-data">Apagar e reiniciar</button></div></div></div>`;
  $('#settings-theme').onclick=()=>$('#theme-toggle').click();$('#export-backup').onclick=()=>downloadJSON({app:'BACEN Estudos TI',exportedAt:new Date().toISOString(),version:DATA.metadata.version,state},`backup-bacen-ti-${isoDate()}.json`);$('#open-import').onclick=()=>$('#import-dialog').showModal();$('#enable-notifications').onclick=enableNotifications;$('#test-phrase').onclick=()=>toast(randomPhrase());$('#inactive-hours').onchange=e=>{state.settings.notifications.inactivityHours=clamp(Number(e.target.value||24),1,336);save();syncReminderConfig()};$('#reset-data').onclick=()=>{if(confirm('Apagar todo o progresso salvo neste navegador?')){state=resetState(DATA.config);applyTheme();toast('Progresso reiniciado.');renderConfig()}}
}

async function importBackup(){const f=$('#import-file').files[0];if(!f){toast('Selecione um arquivo JSON.','error');return}try{const data=JSON.parse(await f.text());if(!data.state||!data.state.settings)throw new Error('Arquivo incompatível');const d=createDefaultState(DATA.config),raw=data.state;state={...d,...raw,weeklyPlans:{...d.weeklyPlans,...(raw.weeklyPlans||{})},lessonLinks:{...d.lessonLinks,...(raw.lessonLinks||{})},discursiva:{...d.discursiva,...(raw.discursiva||{})},settings:{...d.settings,...raw.settings,dayMinutes:{...d.settings.dayMinutes,...(raw.settings?.dayMinutes||{})},dayStartTimes:{...d.settings.dayStartTimes,...(raw.settings?.dayStartTimes||{})},saturday:{...d.settings.saturday,...(raw.settings?.saturday||{})},finalSprint:{...d.settings.finalSprint,...(raw.settings?.finalSprint||{}),saturday:{...d.settings.finalSprint.saturday,...(raw.settings?.finalSprint?.saturday||{})}},notifications:{...d.settings.notifications,...(raw.settings?.notifications||{})}}};if(!state.settings.objectiveExamDate&&state.settings.targetDate)state.settings.objectiveExamDate=state.settings.targetDate;state.settings.targetDate=state.settings.objectiveExamDate||'';save();applyTheme();$('#import-dialog').close();toast('Backup importado com sucesso.');render()}catch(e){toast(`Não foi possível importar: ${e.message}`,'error')}}

function populateTimerSubjects(){const sel=$('#timer-subject');sel.innerHTML=[...objectiveSubjects(),'Atualidades','Prova Discursiva'].map(s=>`<option>${esc(s)}</option>`).join('')}
function updateTimerUI(){const sec=timer.elapsed+(timer.running?Math.floor((Date.now()-timer.startedAt)/1000):0),txt=secondsToClock(sec,true);$('#timer-display').textContent=txt;$('#timer-mini-label').textContent=txt}
function startTimer(){if(timer.running)return;timer.running=true;timer.startedAt=Date.now();timer.interval=setInterval(updateTimerUI,1000);updateTimerUI()}
function pauseTimer(){if(!timer.running)return;timer.elapsed+=Math.floor((Date.now()-timer.startedAt)/1000);timer.running=false;clearInterval(timer.interval);timer.interval=null;updateTimerUI()}
function finishTimer(){pauseTimer();if(timer.elapsed<1){toast('Inicie o cronômetro antes de salvar.','error');return}state.timerSessions.push({id:uid('focus'),date:isoDate(),subject:$('#timer-subject').value,note:$('#timer-note').value.trim(),seconds:timer.elapsed,createdAt:new Date().toISOString()});save();toast(`Sessão de ${secondsToClock(timer.elapsed)} salva.`);timer.elapsed=0;$('#timer-note').value='';updateTimerUI();$('#timer-dialog').close();if(route==='dashboard'||route==='hoje')render()}

const ROUTES={
 dashboard:{title:'Dashboard',eyebrow:'Visão geral',render:renderDashboard},hoje:{title:'Hoje',eyebrow:'Plano do dia',render:renderToday},plano:{title:'Plano de estudos',eyebrow:'Rateio inteligente',render:renderPlan},calendario:{title:'Calendário',eyebrow:'Agenda semanal por aula',render:renderCalendar},edital:{title:'Edital verticalizado',eyebrow:'Base 2024',render:renderEdital},curso:{title:'Curso Gran',eyebrow:'916 videoaulas',render:renderCourse},questoes:{title:'Questões',eyebrow:'Desempenho',render:renderQuestions},revisoes:{title:'Revisões',eyebrow:'Consolidação',render:renderReviews},discursiva:{title:'Prova discursiva',eyebrow:'100 pares de temas',render:renderDiscursive},cobertura:{title:'Cobertura do curso',eyebrow:'Lacunas',render:renderCoverage},config:{title:'Configurações',eyebrow:'Dados e backup',render:renderConfig}
};

boot();
