function prep(canvas){const dpr=Math.max(1,window.devicePixelRatio||1),rect=canvas.getBoundingClientRect();canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w:rect.width,h:rect.height}}
function css(name){return getComputedStyle(document.documentElement).getPropertyValue(name).trim()}
export function barChart(canvas,labels,values,{max=null}={}){
  if(!canvas)return;const{ctx,w,h}=prep(canvas);ctx.clearRect(0,0,w,h);const pad={l:42,r:14,t:14,b:58};const W=w-pad.l-pad.r,H=h-pad.t-pad.b;const vmax=max||Math.max(...values,1);ctx.strokeStyle=css('--line');ctx.fillStyle=css('--muted');ctx.font='11px system-ui';ctx.textAlign='right';for(let i=0;i<=4;i++){const y=pad.t+H-(H*i/4);ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillText(Math.round(vmax*i/4),pad.l-7,y+4)}
  const bw=Math.max(10,W/values.length*.58),gap=W/values.length;values.forEach((v,i)=>{const x=pad.l+gap*i+(gap-bw)/2,bh=H*(v/vmax),y=pad.t+H-bh;const g=ctx.createLinearGradient(0,y,0,y+bh);g.addColorStop(0,css('--accent'));g.addColorStop(1,css('--accent-2'));ctx.fillStyle=g;ctx.beginPath();ctx.roundRect(x,y,bw,bh,5);ctx.fill();ctx.save();ctx.translate(x+bw/2,h-9);ctx.rotate(-.45);ctx.fillStyle=css('--muted');ctx.font='10px system-ui';ctx.textAlign='right';ctx.fillText(labels[i],0,0);ctx.restore()})
}
export function donutChart(canvas,values,labels){
  if(!canvas)return;const{ctx,w,h}=prep(canvas);ctx.clearRect(0,0,w,h);const total=values.reduce((a,b)=>a+b,0)||1,cx=w/2,cy=h/2,r=Math.min(w,h)*.31;const colors=[css('--accent'),css('--accent-2'),css('--warn'),css('--danger'),'#5bc0eb','#a78bfa'];let a=-Math.PI/2;values.forEach((v,i)=>{const da=v/total*Math.PI*2;ctx.strokeStyle=colors[i%colors.length];ctx.lineWidth=Math.max(15,r*.28);ctx.beginPath();ctx.arc(cx,cy,r,a,a+da);ctx.stroke();a+=da});ctx.fillStyle=css('--text');ctx.font='800 26px system-ui';ctx.textAlign='center';ctx.fillText(`${Math.round(values[0]/total*100)}%`,cx,cy+4);ctx.font='11px system-ui';ctx.fillStyle=css('--muted');ctx.fillText(labels[0],cx,cy+23)
}
