import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {cebraspeExpectedScore,cebraspePracticeScore,thematicBlockProjection,discursiveProjection,filterRankingCandidates,equivalentPosition,percentile,finalScore} from '../js/ranking.js';

const root=path.resolve(new URL('..',import.meta.url).pathname);
const ranking=JSON.parse(fs.readFileSync(path.join(root,'data/bacen-ranking-2024.json'),'utf8'));
const edital=JSON.parse(fs.readFileSync(path.join(root,'data/edital.json'),'utf8'));
assert.equal(ranking.candidatos.length,150,'ranking deve ter 150 candidatos');
assert.equal(ranking.meta.anonimizado,true,'ranking deve estar anonimizado');
assert.equal(Object.prototype.hasOwnProperty.call(ranking.candidatos[0],'nome'),false,'nome não deve ser publicado');
assert.ok(Math.abs(cebraspeExpectedScore(50,.9)-42.5)<1e-9,'fórmula P1 divergente');
assert.equal(cebraspePracticeScore(80,20),70,'nota líquida de treino divergente');
const lp=edital.find(x=>x.materia==='Língua Portuguesa'&&x.item==='1');
const p1Subjects=['Língua Portuguesa','Noções de Lógica e Estatística','Direito Administrativo','Fundamentos de Macroeconomia e Microeconomia'];
const proj=thematicBlockProjection({topicRows:[{topicId:lp.id,questions:100,correct:80,errors:20,accuracy:.8}],subjectRows:[{subject:'Língua Portuguesa',questions:100,correct:80,errors:20}],edital,subjects:p1Subjects,items:50});
assert.equal(proj.questions,100);assert.ok(proj.coverage>0&&proj.coverage<1);assert.ok(Number.isFinite(proj.score));assert.equal(proj.topics.find(x=>x.topicId===lp.id).practiceScore,70);
const disc=discursiveProjection([{p3Score:24,createdAt:'2026-08-01'},{p3Score:27,createdAt:'2026-08-02'},{p3Score:null,createdAt:'2026-08-03'}],'p3Score',30);assert.equal(disc.count,2);assert.equal(disc.score,25.5);
assert.equal(filterRankingCandidates(ranking.candidatos,'pcd').every(x=>String(x.modalidade).toLowerCase().includes('pcd')),true);
assert.equal(equivalentPosition(999,ranking.candidatos,'final'),1);assert.ok(percentile(175,ranking.candidatos,'final')>=.99);assert.equal(finalScore({p1:40,p2:55,p3:25,p4:40,titulos:2}),162);
console.log('ranking-smoke: OK');
