import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve(new URL('..',import.meta.url).pathname),read=f=>fs.readFileSync(path.join(root,f),'utf8'),json=f=>JSON.parse(read(f));
const html=read('index.html'),css=read('css/style.css'),app=read('js/app.js'),sw=read('service-worker.js'),manifest=json('manifest.webmanifest'),ranking=json('data/bacen-ranking-2024.json'),meta=json('data/metadata.json'),edital=json('data/edital.json'),pesos=json('data/pesos.json');
assert.equal(html.includes('id="bottom-nav"'),false,'barra inferior ainda existe');assert.equal(html.includes('data-contest="bb"'),false,'Banco do Brasil ainda aparece no HTML');assert.equal(app.includes('switchContest'),false,'motor multi-concurso ainda existe');assert.ok(html.includes('class="menu-svg"')&&css.includes('.menu-svg')&&css.includes('stroke:currentColor'),'menu mobile SVG inconsistente');
assert.equal(meta.version,'2.1.0');assert.equal(meta.updatedAt,'2026-08-17');assert.equal(manifest.short_name,'BACEN TI');assert.equal(ranking.candidatos.length,150);assert.equal(ranking.meta.anonimizado,true);assert.equal(json('data/curso-gran.json').length,916);assert.equal(json('data/frases-motivacionais.json').length,500);assert.equal(json('data/temas-discursiva.json').length,100);
for(const file of ['data/curso-bb.json','data/edital-bb.json','data/metadata-bb.json','data/concursos.json'])assert.equal(fs.existsSync(path.join(root,file)),false,`arquivo removido ainda existe: ${file}`);
const proofCounts=Object.fromEntries(['P1','P2','P3','P4'].map(p=>[p,edital.filter(x=>x.prova===p).length]));assert.ok(proofCounts.P1&&proofCounts.P2&&proofCounts.P3===1&&proofCounts.P4===1,'separação P1/P2/P3/P4 inválida');for(const subject of Object.keys(pesos))assert.ok(edital.some(x=>x.materia===subject&&['P1','P2'].includes(x.prova)),`matéria objetiva sem prova: ${subject}`);
assert.ok(app.includes('thematicBlockProjection')&&app.includes('p3Score')&&app.includes('p4Score'),'ranking temático/discursivo ausente');assert.ok(css.includes('.proof-navigation-grid')&&css.includes('.thematic-topic'),'layout P1/P2/P3/P4 ausente');assert.ok(sw.includes('bacen-ti-v2.1')&&!sw.includes('edital-bb'),'cache PWA incorreto');assert.ok(css.includes('prefers-reduced-motion'),'acessibilidade de movimento reduzido ausente');
console.log('ui-static: OK');
